apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-service-deploy
spec:
  selector:
    matchLabels:
      app: dashboard-service
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: dashboard-service
    spec:
      containers:
        - name: dashboard-service
          image: nikmohan81/dashboard-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

---

apiVersion: v1
kind: Service
metadata:
  name: dashboard-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: dashboard-service

  ports:
    - name: http
      port: 9060

  type: ClusterIP

