server:
  port: 9060
spring:
  profiles:
    active: dev
  cloud.stream:
    bindings:
      input-tasks:
        destination: tasks
        group: dashboard

      input-goals:
        destination: goals
        group: dashboard

      input-dashboard:
        destination: dashboard
        group: dashboard
        consumer:
          maxAttempts: 3
          backOffInitialInterval: 1000
          backOffMaxInterval: 20000
          backOffMultiplier: 3.0
    defaultBinder: rabbit
    default.contentType: application/json




goal.score:
  easy: 10
  moderate: 25
  extreme: 50
deferPenalty: 6
resumeBonus: 1


---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

---
spring:
  profile: prod
  data:
    mongodb:
      host: hourglassdb-service
      port: 27017
      database: hourglass
  cloud.stream:
    kafka.binder:
      brokers: kafka
      defaultBrokerPort: 9093
spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest






