server:
  port: 9060
spring:
  profiles:
    active: dev
  cloud.stream:
    bindings:
      input-tasks:
        destination: tasks
        group: dashboard

      input-goals:
        destination: goals
        group: dashboard

      input-dashboard:
        destination: dashboard
        group: dashboard
        consumer:
          maxAttempts: 3
          backOffInitialInterval: 1000
          backOffMaxInterval: 20000
          backOffMultiplier: 3.0

goal.score:
  easy: 10
  moderate: 25
  extreme: 50
deferPenalty: 6
resumeBonus: 1


---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
  cloud.stream:
    kafka.binder:
      brokers: localhost

---
spring:
  profile: prod
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: hourglass
  cloud.stream:
    kafka.binder:
      brokers: kafka






